--------------------------------------------------------
--  File created - Thursday-May-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NOTIFICATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."NOTIFICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_AIRLINE
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_AIRLINE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICES
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_INVOICES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICE_ATTACHMENT
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_INVOICE_ATTACHMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_PRODUCT_TYPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RATES
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_RATES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROOM_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_ROOM_TYPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERVICE_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_SERVICE_TYPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SUPPLIER
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_SUPPLIER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SUPPLIER_PRODUCT
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_SUPPLIER_PRODUCT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_UPLOADED_INVOICE_FILE
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."SEQ_UPLOADED_INVOICE_FILE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVELUSER_SCREENS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."TRAVELUSER_SCREENS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVELUSER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAVEL"."TRAVELUSER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AIRLINE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."AIRLINE" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."CATEGORY" 
   (	"CAT_ID" NUMBER(38,0), 
	"CATEGORY_NAME" VARCHAR2(200), 
	"CATEGORY_ORDER" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONFIG
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."CONFIG" 
   (	"CONFIG_ID" NUMBER(38,0), 
	"CONFIG_NAME" VARCHAR2(100), 
	"CONFIG_VALUE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVOICES
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."INVOICES" 
   (	"ID" NUMBER(22,0), 
	"INVOICE_NUMBER" VARCHAR2(100), 
	"BOOKING_FILE_NUMBER" VARCHAR2(100), 
	"DEPARTURE_DATE" DATE, 
	"ARRIVAL_DATE" DATE, 
	"EMPLOYEE_ID" VARCHAR2(100), 
	"COST_CENTER" VARCHAR2(100), 
	"COST_CENTER_DEPARTMENT" VARCHAR2(100), 
	"PASSENGER_NAME" VARCHAR2(300), 
	"SERVICE_TYPE" VARCHAR2(300), 
	"SERVICE_DESC" VARCHAR2(300), 
	"ROUTING" VARCHAR2(300), 
	"INTER_DOM" VARCHAR2(100), 
	"CHECK_IN" DATE, 
	"CHECK_OUT" DATE, 
	"NUMBER_OF_NIGHTS" NUMBER(10,0), 
	"NUMBER_OF_ROOMS" NUMBER(10,0), 
	"AIRLINE" VARCHAR2(300), 
	"ROOM_TYPE" VARCHAR2(300), 
	"SUPPLIER_NAME" VARCHAR2(300), 
	"NET_AMOUNT" NUMBER(22,2), 
	"OPERATION_FEES" NUMBER(22,2), 
	"TOTAL_AMOUNT" NUMBER(22,2), 
	"TICKET_NO" VARCHAR2(300), 
	"TRAVEL_FORM_NUMBER" VARCHAR2(300), 
	"DESCRIPTION" VARCHAR2(300), 
	"FROM" DATE, 
	"TO" DATE, 
	"UPLOADED_INVOICE_FILE_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVOICES_TEMP
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."INVOICES_TEMP" 
   (	"INVOICE_ORDER" NUMBER(22,0), 
	"TRANSACTION_ID" VARCHAR2(100), 
	"INVOICE_NUMBER" VARCHAR2(100), 
	"BOOKING_FILE_NUMBER" VARCHAR2(100), 
	"DEPARTURE_DATE" DATE, 
	"ARRIVAL_DATE" DATE, 
	"EMPLOYEE_ID" VARCHAR2(100), 
	"COST_CENTER" VARCHAR2(100), 
	"COST_CENTER_DEPARTMENT" VARCHAR2(100), 
	"PASSENGER_NAME" VARCHAR2(300), 
	"SERVICE_TYPE" VARCHAR2(300), 
	"SERVICE_DESC" VARCHAR2(300), 
	"ROUTING" VARCHAR2(300), 
	"INTER_DOM" VARCHAR2(100), 
	"CHECK_IN" DATE, 
	"CHECK_OUT" DATE, 
	"NUMBER_OF_NIGHTS" NUMBER(10,0), 
	"NUMBER_OF_ROOMS" NUMBER(10,0), 
	"AIRLINE" VARCHAR2(300), 
	"ROOM_TYPE" VARCHAR2(300), 
	"SUPPLIER_NAME" VARCHAR2(300), 
	"NET_AMOUNT" NUMBER(22,2), 
	"OPERATION_FEES" NUMBER(22,2), 
	"TOTAL_AMOUNT" NUMBER(22,2), 
	"TICKET_NO" VARCHAR2(300), 
	"TRAVEL_FORM_NUMBER" VARCHAR2(300), 
	"DESCRIPTION" VARCHAR2(300), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"UPLOADED_INVOICE_FILE_ID" NUMBER(22,0), 
	"EMPLOYEE_DEPARTMENT" VARCHAR2(100), 
	"INVOICE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVOICE_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."INVOICE_ATTACHMENT" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"CONTENT" BLOB, 
	"TYPE" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"UPLOADED_INVOICE_FILE_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."NOTIFICATION" 
   (	"ID" NUMBER, 
	"ATTACH_FILE" BLOB, 
	"SUBJECT" VARCHAR2(200), 
	"TEMPLATENAME" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ATTACH_FILE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUCT_TYPE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."PRODUCT_TYPE" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500), 
	"SERVICE_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RATES
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."RATES" 
   (	"ID" NUMBER(22,0), 
	"SUPPLIER_PRODUCT_ID" NUMBER(22,0), 
	"RATE" NUMBER(22,2), 
	"ROOM_TYPE_ID" NUMBER(22,0), 
	"AIRLINE_ID" NUMBER(22,0), 
	"YEAR" NUMBER(5,0), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOM_TYPE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."ROOM_TYPE" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEQUENCE_TABLE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."SEQUENCE_TABLE" 
   (	"SEQ_NAME" VARCHAR2(100), 
	"SEQ_COUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_TYPE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."SERVICE_TYPE" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."SUPPLIER" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER_PRODUCT
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."SUPPLIER_PRODUCT" 
   (	"ID" NUMBER(22,0), 
	"SUPPLIER_ID" NUMBER(22,0), 
	"PRODUCT_ID" NUMBER(22,0), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SYSTEM_SCREENS
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."SYSTEM_SCREENS" 
   (	"SCREEN_ID" NUMBER(22,0), 
	"SCREEN_NAME" VARCHAR2(100), 
	"SCREEN_URL" VARCHAR2(256), 
	"CATEGORY_ID" NUMBER(*,0), 
	"SCREEN_ORDER" NUMBER(32,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."TEST" 
   (	"INVOICE_NUMBER" NUMBER(*,0), 
	"TRANSACTION_ID" VARCHAR2(100), 
	"NAME1" VARCHAR2(100), 
	"DATE1" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TMS_USER
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."TMS_USER" 
   (	"EMPLOYEE_ID" NUMBER(22,0), 
	"FULLNAME" VARCHAR2(200), 
	"ACCOUNTNAME" VARCHAR2(200), 
	"EMAIL" VARCHAR2(100), 
	"PHONE" VARCHAR2(20), 
	"DEPARTMENT" VARCHAR2(100), 
	"COSTCENTER" VARCHAR2(50), 
	"COMMENTS" VARCHAR2(300), 
	"EMPLOYEE_TYPE" VARCHAR2(25), 
	"STATUS" NUMBER(1,0), 
	"STAFFID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UPLOADED_INVOICE_FILE
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" 
   (	"ID" NUMBER(22,0), 
	"NAME" VARCHAR2(300), 
	"CONTENT" BLOB, 
	"TYPE" VARCHAR2(300), 
	"MODIFICATION_DATE" DATE, 
	"SYSTEM_USER" VARCHAR2(300), 
	"APPROVED" NUMBER(1,0), 
	"REJECTION_REASON" VARCHAR2(300), 
	"ACTION_TAKER" VARCHAR2(300), 
	"ACTION_TAKEN_DATE" DATE, 
	"TEMPLATE_TABLE" NUMBER(1,0), 
	"INVOICES_MONTH" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERSCREENS
--------------------------------------------------------

  CREATE TABLE "TRAVEL"."USERSCREENS" 
   (	"EMPLOYEE_ID" NUMBER(22,0), 
	"SCREEN_ID" NUMBER, 
	"ADDMODE" NUMBER(1,0), 
	"EDITMODE" NUMBER(1,0), 
	"DELETEMODE" NUMBER(1,0), 
	"ID" NUMBER(*,0), 
	"VIEWMODE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View TESTYYY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TRAVEL"."TESTYYY" ("INVOICE_ORDER", "TRANSACTION_ID", "INVOICE_NUMBER", "BOOKING_FILE_NUMBER", "DEPARTURE_DATE", "ARRIVAL_DATE", "EMPLOYEE_ID", "COST_CENTER", "COST_CENTER_DEPARTMENT", "PASSENGER_NAME", "SERVICE_TYPE", "SERVICE_DESC", "ROUTING", "INTER_DOM", "CHECK_IN", "CHECK_OUT", "NUMBER_OF_NIGHTS", "NUMBER_OF_ROOMS", "AIRLINE", "ROOM_TYPE", "SUPPLIER_NAME", "NET_AMOUNT", "OPERATION_FEES", "TOTAL_AMOUNT", "TICKET_NO", "TRAVEL_FORM_NUMBER", "DESCRIPTION", "FROM_DATE", "TO_DATE", "UPLOADED_INVOICE_FILE_ID", "EMPLOYEE_DEPARTMENT", "INVOICE_DATE", "ERROR_DESCRIPTION") AS 
  SELECT  INVOICES_TEMP."INVOICE_ORDER",INVOICES_TEMP."TRANSACTION_ID",INVOICES_TEMP."INVOICE_NUMBER",INVOICES_TEMP."BOOKING_FILE_NUMBER",INVOICES_TEMP."DEPARTURE_DATE",INVOICES_TEMP."ARRIVAL_DATE",INVOICES_TEMP."EMPLOYEE_ID",INVOICES_TEMP."COST_CENTER",INVOICES_TEMP."COST_CENTER_DEPARTMENT",INVOICES_TEMP."PASSENGER_NAME",INVOICES_TEMP."SERVICE_TYPE",INVOICES_TEMP."SERVICE_DESC",INVOICES_TEMP."ROUTING",INVOICES_TEMP."INTER_DOM",INVOICES_TEMP."CHECK_IN",INVOICES_TEMP."CHECK_OUT",INVOICES_TEMP."NUMBER_OF_NIGHTS",INVOICES_TEMP."NUMBER_OF_ROOMS",INVOICES_TEMP."AIRLINE",INVOICES_TEMP."ROOM_TYPE",INVOICES_TEMP."SUPPLIER_NAME",INVOICES_TEMP."NET_AMOUNT",INVOICES_TEMP."OPERATION_FEES",INVOICES_TEMP."TOTAL_AMOUNT",INVOICES_TEMP."TICKET_NO",INVOICES_TEMP."TRAVEL_FORM_NUMBER",INVOICES_TEMP."DESCRIPTION",INVOICES_TEMP."FROM_DATE",INVOICES_TEMP."TO_DATE",INVOICES_TEMP."UPLOADED_INVOICE_FILE_ID",INVOICES_TEMP."EMPLOYEE_DEPARTMENT",INVOICES_TEMP."INVOICE_DATE" ,'ss' ERROR_DESCRIPTION  FROM UPLOADED_INVOICE_FILE INNER JOIN INVOICES_TEMP  ON UPLOADED_INVOICE_FILE.ID = INVOICES_TEMP.UPLOADED_INVOICE_FILE_ID  WHERE add_months(TO_DATE('26/'  || UPLOADED_INVOICE_FILE.INVOICES_MONTH, 'dd/mm/yyyy'), -1) <= INVOICES_TEMP.INVOICE_DATE    AND TO_DATE('25/'  || UPLOADED_INVOICE_FILE.INVOICES_MONTH, 'dd/mm/yyyy') >= INVOICES_TEMP.INVOICE_DATE    AND UPLOADED_INVOICE_FILE.INVOICES_MONTH LIKE '01/2011';
REM INSERTING into TRAVEL.AIRLINE
SET DEFINE OFF;
REM INSERTING into TRAVEL.CATEGORY
SET DEFINE OFF;
Insert into TRAVEL.CATEGORY (CAT_ID,CATEGORY_NAME,CATEGORY_ORDER) values (1,'Administration',2);
Insert into TRAVEL.CATEGORY (CAT_ID,CATEGORY_NAME,CATEGORY_ORDER) values (2,'Travel Management System',1);
REM INSERTING into TRAVEL.CONFIG
SET DEFINE OFF;
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (1,'LDAP_USERS_SB','OU=DPT,DC=vfdev,DC=com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (2,'LDAP_URL','ldap://localhost:389');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (3,'LDAP_DOMAIN_NAME','vfdev.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (4,'MAIL_PORT','587');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (5,'MAIL_HOST','smtp.gmail.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (6,'MAIL_FROM','vodafoneincidentmanagement@gmail.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (7,'MAIL_AUTH','true');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (8,'MAIL_USERNAME','ahmedmis2014@gmail.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (9,'MAIL_PASSWORD','/pxYak0n00PwLIjPLy4n3g==');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (10,'MAIL_DEBUG','true');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (11,'SYSTEM_URL','http://localhost:7001/IncidentManagment/login.xhtml');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (12,'SYS_ADMIN','admin');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (13,'SYS_PASSWORD','123');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (14,'TravelTeam','vftestmails@gmail.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (15,'AgentTeam','vftestmails@gmail.com');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (16,'PROVIDER_URL','http://localhost:7007');
Insert into TRAVEL.CONFIG (CONFIG_ID,CONFIG_NAME,CONFIG_VALUE) values (17,'DBConnection','jdbc:oracle:thin:fleet/fleet@192.168.1.16:1521:orcl');
REM INSERTING into TRAVEL.INVOICES
SET DEFINE OFF;
REM INSERTING into TRAVEL.INVOICES_TEMP
SET DEFINE OFF;
REM INSERTING into TRAVEL.INVOICE_ATTACHMENT
SET DEFINE OFF;
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (1,'Travel System (Requirement Document V8).docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',to_date('03-MAY-16','DD-MON-RR'),'syehia1',5);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (2,'Vodafone Statement From 26 June 15 To 25 July 15.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('03-MAY-16','DD-MON-RR'),'syehia1',5);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (22,'ssss.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',21);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (21,'Travel.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',21);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (24,'Travel System (Requirement Document V7).docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',to_date('04-MAY-16','DD-MON-RR'),'syehia1',22);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (23,'Travel System (Requirement Document V8).docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',to_date('04-MAY-16','DD-MON-RR'),'syehia1',22);
Insert into TRAVEL.INVOICE_ATTACHMENT (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,UPLOADED_INVOICE_FILE_ID) values (25,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',24);
REM INSERTING into TRAVEL.NOTIFICATION
SET DEFINE OFF;
REM INSERTING into TRAVEL.PRODUCT_TYPE
SET DEFINE OFF;
REM INSERTING into TRAVEL.RATES
SET DEFINE OFF;
REM INSERTING into TRAVEL.ROOM_TYPE
SET DEFINE OFF;
REM INSERTING into TRAVEL.SEQUENCE_TABLE
SET DEFINE OFF;
Insert into TRAVEL.SEQUENCE_TABLE (SEQ_NAME,SEQ_COUNT) values ('SERVICE_SEQ',30000);
REM INSERTING into TRAVEL.SERVICE_TYPE
SET DEFINE OFF;
REM INSERTING into TRAVEL.SUPPLIER
SET DEFINE OFF;
REM INSERTING into TRAVEL.SUPPLIER_PRODUCT
SET DEFINE OFF;
REM INSERTING into TRAVEL.SYSTEM_SCREENS
SET DEFINE OFF;
Insert into TRAVEL.SYSTEM_SCREENS (SCREEN_ID,SCREEN_NAME,SCREEN_URL,CATEGORY_ID,SCREEN_ORDER) values (1,'Upload Invoices ','travelmanagementsystem/invoiceexcelsheet.xhtml',2,1);
Insert into TRAVEL.SYSTEM_SCREENS (SCREEN_ID,SCREEN_NAME,SCREEN_URL,CATEGORY_ID,SCREEN_ORDER) values (2,'Errors In Request','travelmanagementsystem/invoiceexcelsheet.xhtml',2,2);
REM INSERTING into TRAVEL.TEST
SET DEFINE OFF;
Insert into TRAVEL.TEST (INVOICE_NUMBER,TRANSACTION_ID,NAME1,DATE1) values (12,'123','3234',to_date('03-MAY-16','DD-MON-RR'));
Insert into TRAVEL.TEST (INVOICE_NUMBER,TRANSACTION_ID,NAME1,DATE1) values (13,'123','3234',to_date('03-MAY-16','DD-MON-RR'));
REM INSERTING into TRAVEL.TMS_USER
SET DEFINE OFF;
Insert into TRAVEL.TMS_USER (EMPLOYEE_ID,FULLNAME,ACCOUNTNAME,EMAIL,PHONE,DEPARTMENT,COSTCENTER,COMMENTS,EMPLOYEE_TYPE,STATUS,STAFFID) values (43,'Sara Yehia','syehia1','vftestmails@gmail.com','1003013014','Technology','244',null,'RMSUSER',1,3144);
REM INSERTING into TRAVEL.UPLOADED_INVOICE_FILE
SET DEFINE OFF;
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (1,'yy','tyoe',to_date('03-MAY-16','DD-MON-RR'),'dasds',0,'reason','user',to_date('18-MAY-16','DD-MON-RR'),null,'01/2011');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (4,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('03-MAY-16','DD-MON-RR'),'syehia1',0,null,null,to_date('03-MAY-16','DD-MON-RR'),null,'01/2011');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (5,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('03-MAY-16','DD-MON-RR'),'syehia1',null,null,null,to_date('03-MAY-16','DD-MON-RR'),null,'01/2011');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (21,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',null,null,null,null,1,'01/2011');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (22,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',null,null,null,null,1,'03/2013');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (23,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',null,null,null,null,1,'06/2016');
Insert into TRAVEL.UPLOADED_INVOICE_FILE (ID,NAME,TYPE,MODIFICATION_DATE,SYSTEM_USER,APPROVED,REJECTION_REASON,ACTION_TAKER,ACTION_TAKEN_DATE,TEMPLATE_TABLE,INVOICES_MONTH) values (24,'template.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',to_date('04-MAY-16','DD-MON-RR'),'syehia1',null,null,null,null,1,'03/2013');
REM INSERTING into TRAVEL.USERSCREENS
SET DEFINE OFF;
Insert into TRAVEL.USERSCREENS (EMPLOYEE_ID,SCREEN_ID,ADDMODE,EDITMODE,DELETEMODE,ID,VIEWMODE) values (43,1,1,1,1,1,1);
--------------------------------------------------------
--  DDL for Index SERVICE_PRODUCTNAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."SERVICE_PRODUCTNAME_UNIQUE" ON "TRAVEL"."PRODUCT_TYPE" ("SERVICE_ID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYSTEM_SCREENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."SYSTEM_SCREENS_PK" ON "TRAVEL"."SYSTEM_SCREENS" ("SCREEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONFIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."CONFIG_PK" ON "TRAVEL"."CONFIG" ("CONFIG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."NOTIFICATION_PK" ON "TRAVEL"."NOTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INVOICES_TEMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."INVOICES_TEMP_PK" ON "TRAVEL"."INVOICES_TEMP" ("INVOICE_ORDER", "TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERSCREENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."USERSCREENS_PK" ON "TRAVEL"."USERSCREENS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."CATEGORY_PK" ON "TRAVEL"."CATEGORY" ("CAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TMS_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."TMS_USER_PK" ON "TRAVEL"."TMS_USER" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_SUPPIER_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."PRODUCT_SUPPIER_UNIQUE" ON "TRAVEL"."SUPPLIER_PRODUCT" ("PRODUCT_ID", "SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."TEST_PK" ON "TRAVEL"."TEST" ("INVOICE_NUMBER", "TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0014231
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAVEL"."SYS_C0014231" ON "TRAVEL"."TMS_USER" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RATES
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."RATES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."RATES" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."RATES" MODIFY ("RATE" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."RATES" MODIFY ("SUPPLIER_PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."RATES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER_PRODUCT
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" ADD CONSTRAINT "PRODUCT_SUPPIER_UNIQUE" UNIQUE ("PRODUCT_ID", "SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYSTEM_SCREENS
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SYSTEM_SCREENS" ADD CONSTRAINT "SYSTEM_SCREENS_PK" PRIMARY KEY ("SCREEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SYSTEM_SCREENS" MODIFY ("SCREEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("INVOICE_NUMBER", "TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."TEST" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."TEST" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM_TYPE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."ROOM_TYPE" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."ROOM_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."ROOM_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."ROOM_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."CATEGORY" MODIFY ("CAT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SUPPLIER" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SUPPLIER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SUPPLIER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."SUPPLIER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."INVOICES" MODIFY ("UPLOADED_INVOICE_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_TYPE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SERVICE_TYPE" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SERVICE_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."SERVICE_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."SERVICE_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONFIG
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."CONFIG" ADD CONSTRAINT "CONFIG_PK" PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."CONFIG" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."NOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEQUENCE_TABLE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SEQUENCE_TABLE" MODIFY ("SEQ_COUNT" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."SEQUENCE_TABLE" MODIFY ("SEQ_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" MODIFY ("UPLOADED_INVOICE_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERSCREENS
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."USERSCREENS" ADD CONSTRAINT "USERSCREENS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."USERSCREENS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."USERSCREENS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TMS_USER
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."TMS_USER" ADD UNIQUE ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."TMS_USER" ADD CONSTRAINT "TMS_USER_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."TMS_USER" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."TMS_USER" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" ADD CONSTRAINT "SERVICE_PRODUCTNAME_UNIQUE" UNIQUE ("SERVICE_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AIRLINE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."AIRLINE" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."AIRLINE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."AIRLINE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."AIRLINE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICES_TEMP
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICES_TEMP" ADD CONSTRAINT "INVOICES_TEMP_PK" PRIMARY KEY ("INVOICE_ORDER", "TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."INVOICES_TEMP" MODIFY ("UPLOADED_INVOICE_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICES_TEMP" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."INVOICES_TEMP" MODIFY ("INVOICE_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UPLOADED_INVOICE_FILE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAVEL"."UPLOADED_INVOICE_FILE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICES" ADD CONSTRAINT "UPLOAD_INVOICE_FILE_FK_INVOIC" FOREIGN KEY ("UPLOADED_INVOICE_FILE_ID")
	  REFERENCES "TRAVEL"."UPLOADED_INVOICE_FILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICES_TEMP
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICES_TEMP" ADD CONSTRAINT "UPLOAD_FILE_FK_TEMP_INVOIC" FOREIGN KEY ("UPLOADED_INVOICE_FILE_ID")
	  REFERENCES "TRAVEL"."UPLOADED_INVOICE_FILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."INVOICE_ATTACHMENT" ADD CONSTRAINT "UPLOAD_INVOICE_FILE_FK_ATTACH" FOREIGN KEY ("UPLOADED_INVOICE_FILE_ID")
	  REFERENCES "TRAVEL"."UPLOADED_INVOICE_FILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."PRODUCT_TYPE" ADD CONSTRAINT "PRODUCT_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "TRAVEL"."SERVICE_TYPE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RATES
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."RATES" ADD CONSTRAINT "AIRLINE_FK_RATES" FOREIGN KEY ("AIRLINE_ID")
	  REFERENCES "TRAVEL"."AIRLINE" ("ID") ENABLE;
  ALTER TABLE "TRAVEL"."RATES" ADD CONSTRAINT "ROOM_TYPE_FK_RATES" FOREIGN KEY ("ROOM_TYPE_ID")
	  REFERENCES "TRAVEL"."ROOM_TYPE" ("ID") ENABLE;
  ALTER TABLE "TRAVEL"."RATES" ADD CONSTRAINT "SUPPLIER_PRODUCT_FK_RATES" FOREIGN KEY ("SUPPLIER_PRODUCT_ID")
	  REFERENCES "TRAVEL"."SUPPLIER_PRODUCT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPPLIER_PRODUCT
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" ADD CONSTRAINT "SUPPLIER_PRODUCT_FK_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "TRAVEL"."PRODUCT_TYPE" ("ID") ENABLE;
  ALTER TABLE "TRAVEL"."SUPPLIER_PRODUCT" ADD CONSTRAINT "SUPPLIER_PRODUCT_FK_SUPPLIER" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "TRAVEL"."SUPPLIER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYSTEM_SCREENS
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."SYSTEM_SCREENS" ADD CONSTRAINT "SYSTEM_SCREENS_FK1" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "TRAVEL"."CATEGORY" ("CAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERSCREENS
--------------------------------------------------------

  ALTER TABLE "TRAVEL"."USERSCREENS" ADD CONSTRAINT "USERSCREENS_FK1" FOREIGN KEY ("SCREEN_ID")
	  REFERENCES "TRAVEL"."SYSTEM_SCREENS" ("SCREEN_ID") ENABLE;
  ALTER TABLE "TRAVEL"."USERSCREENS" ADD CONSTRAINT "USERSCREENS_FK_USER" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "TRAVEL"."TMS_USER" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Procedure TEST2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "TRAVEL"."TEST2" IS
       i   NUMBER := 0;
       
      CURSOR cur_invoice is   (SELECT * FROM test);
    BEGIN
       FOR rec IN cur_invoice
       LOOP
          i := i + 1;
          DBMS_OUTPUT.put_line ('Record ' || i || ' is emp ' || rec.INVOICE_NUMBER);
          INSERT INTO "TRAVEL"."TEST" (INVOICE_NUMBER, TRANSACTION_ID, NAME1, DATE1) VALUES 
(rec.INVOICE_NUMBER+i, rec.TRANSACTION_ID, rec.NAME1, rec.DATE1);
       END LOOP;
  
      DBMS_OUTPUT.put_line ('Procedure Looping Example is done');
      
   END;
   

/
--------------------------------------------------------
--  DDL for Procedure TESTSTORED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "TRAVEL"."TESTSTORED" 
IS
BEGIN
  
  
INSERT INTO "TRAVEL"."TEST" (INVOICE_NUMBER, TRANSACTION_ID, NAME1, DATE1) VALUES 
('12', '123', '3234', TO_DATE('2016-05-03 09:07:15', 'YYYY-MM-DD HH24:MI:SS'));


END;

/
